"use client"

import type { Icon } from "@phosphor-icons/react"
import {
  AppWindowIcon,
  ArrowsDownUpIcon,
  ChartBarIcon,
  ChartLineIcon,
  ChartLineUpIcon,
  ChartPieIcon,
  ChartPolarIcon,
  CertificateIcon,
  ChatsCircleIcon,
  CircleIcon,
  CloudIcon,
  CodeIcon,
  CreditCardIcon,
  CursorClickIcon,
  DotsThreeOutlineIcon,
  GaugeIcon,
  HashIcon,
  InfoIcon,
  LightningIcon,
  ListIcon,
  MegaphoneIcon,
  MinusIcon,
  RocketLaunchIcon,
  RowsIcon,
  SealIcon,
  SparkleIcon,
  SpinnerGapIcon,
  SquaresFourIcon,
  TagIcon,
  TabsIcon,
  TextboxIcon,
  ToggleLeftIcon,
  TrendUpIcon,
  UserIcon,
  WarningCircleIcon,
} from "@phosphor-icons/react"
import type { CatalogComponentSlug } from "@/features/catalog/constants/components"

export const catalogNavIcons: Record<CatalogComponentSlug, Icon> = {
  buttons: CursorClickIcon,
  badges: SealIcon,
  "dropdown-menu": DotsThreeOutlineIcon,
  inputs: TextboxIcon,
  "form-controls": ToggleLeftIcon,
  cards: CreditCardIcon,
  alerts: WarningCircleIcon,
  tabs: TabsIcon,
  avatars: UserIcon,
  skeleton: SpinnerGapIcon,
  separator: MinusIcon,
  "scroll-area": ArrowsDownUpIcon,
  code: CodeIcon,
  dialog: AppWindowIcon,
  popover: CloudIcon,
  tooltip: InfoIcon,
  progress: GaugeIcon,
  "stat-card": ChartLineUpIcon,
  "empty-state": CircleIcon,
  "glow-card": SparkleIcon,
  "ascii-background": HashIcon,
  "status-indicator": LightningIcon,
  "area-chart": ChartLineUpIcon,
  "bar-chart": ChartBarIcon,
  "line-chart": ChartLineIcon,
  "pie-chart": ChartPieIcon,
  "radar-chart": ChartPolarIcon,
  sparkline: TrendUpIcon,
  navbar: ListIcon,
  hero: RocketLaunchIcon,
  features: SquaresFourIcon,
  testimonials: ChatsCircleIcon,
  pricing: TagIcon,
  cta: MegaphoneIcon,
  branding: CertificateIcon,
  "bento-grid": SquaresFourIcon,
  footer: RowsIcon,
}

export function getCatalogNavIcon(slug: string) {
  return catalogNavIcons[slug as CatalogComponentSlug]
}
